- name: Run LAMP setup bash script and create a cron job that runs uptime
  hosts: remote_nodes
  vars_files:
    - variables.yaml
  become: yes
  tasks:
    - name: Transfer script file to Remote node
      copy:
        src: "{{ main_node.playbook_dir }}/lamp_setup.sh"
        dest: /tmp/lamp_setup.sh
        mode: "0755"

    - name: Execute the script on the Remote Node
      shell: /tmp/lamp_setup.sh
      args:
        executable: /bin/bash

    - name: Check if hostname is accessible
      uri:
        url: "http://{{ remote_node.hostname }}/"
        method: GET
        status_code: 200
      register: response
      until: response.status == 200
      retries: 5
      delay: 5

    - name: Display result
      debug:
        msg: "Hostname is accessible"
      when: response.status == 200

    - name: Create a cron job to check server (remote node's) uptime every day at 12 am
      cron:
        name: "Check Server Uptime"
        minute: 0
        hour: 0
        job: "/usr/bin/uptime >> /var/log/lamp_uptime.log 2>&1"

