- name: Run LAMP setup bash script and create a cron job that runs uptime
  hosts: slave
  become: yes
  tasks:
    - name: Transfer script file to Slave node
      copy:
        src: /home/vagrant/lamp_project_exam/lamp_setup.sh
        dest: /tmp/lamp_setup.sh
        mode: "0755"

    - name: Execute the script on the Slave Node
      shell: /tmp/lamp_setup.sh
      args:
        executable: /bin/bash

    - name: Create a cron job to check server (Slave node's) uptime every day at 12 am
      cron:
        name: "Check Server Uptime"
        minute: 0
        hour: 0
        job: "/usr/bin/uptime"

